el1 = instance_create_layer(x, y, "GUI_Front", obj_ui_electron)
el1.distance_from_player = 128 - 15
el1.rotate_speed = 1
el1.current_angle = 330
el2 = instance_create_layer(x, y, "GUI_Front", obj_ui_electron)
el2.distance_from_player = 130
el2.rotate_speed = 1
el2.current_angle = 120
el3 = instance_create_layer(x, y, "GUI_Front", obj_ui_electron)
el3.distance_from_player = 130
el3.rotate_speed = 1
el3.current_angle = 225